---
abstract: 'plugin to handle signatures from SinFP3 database'
author:
  - 'GomoR <gomor_at_networecon.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-SinFP3-Plugin-Signature
no_index:
  directory:
    - t
    - inc
requires:
  Class::DBI: 0
  Net::SinFP3: 0
  perl: 5.006001
version: 1.00
